### ISSUE TITLE
Command doesnt work

### ISSUE THREAD

**Issue by ac-daman** [tineyi/first_web_scraper#1]
after putting ruby scraper.rb, i get this:

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- HTTParty (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from scraper.rb:1:in `<main>'

**Comment by CodeBrotha** [comment]
In your terminal, run this command: gem install httparty

Then try again. Sorry, should have put that in the readme.

**Comment by ac-daman** [comment]
do i do that first? I just put that in right now, and i got 
Fetching: multi_xml-0.6.0.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

Thanks

**Comment by CodeBrotha** [comment]
First cd into the folder then run it.

**Comment by ac-daman** [comment]
i just cd'd into the lib folder and ran it, got the same error message
tried it after just cd'ing into first_web_scraper-master

**Comment by CodeBrotha** [comment]
What OS are you running? Also are you logged in as an admin user?

**Comment by ac-daman** [comment]
El Capitan, and im the only user, should i run a sudo command?

**Comment by CodeBrotha** [comment]
You really shouldn't use sudo to install gems. Also I just remembered httparty is in the gem file already so this "should" be working right away. I just tried it on my new system, although I'm now on macOS Sierra and it worked. How did you install Ruby?

**Comment by ac-daman** [comment]
ruby 2.0 comes installed on El Capitan

**Comment by CodeBrotha** [comment]
Ah. This is the problem. You need to install Ruby, (and Rails if you want that), either through rbenv or rvm. I recommend rbenv.

Follow this install procedure: https://gorails.com/setup/osx/10.11-el-capitan

**Comment by ac-daman** [comment]
Thank you, did that, and it started working, then showed this:

cannot load such file -- Nokogiri (LoadError)

**Comment by CodeBrotha** [comment]
Sorry, that was my fault, I just added the nokogiri gem to the Gemfile.

Run: gem install nokogiri

**Comment by ac-daman** [comment]
awesome, thank you very very much

**Comment by CodeBrotha** [comment]
Is it running now?

**Comment by ac-daman** [comment]
yeah, im getting stuff like:
Name: Nike Air Max 1 Premium "What The" Pendleton iD | Price: $170

is there somehow I can see where online that is being sold, or is there an index key?

**Comment by CodeBrotha** [comment]
This is specific to nike.com so only that site. If you want to see where else it is being sold, you'll have to write that code on your own. Good idea though, I'm just too busy to even attempt it at the moment.

**Comment by ac-daman** [comment]
Got it, thank you

**Comment by CodeBrotha** [comment]
No, no. Thank YOU! You got me to fix my readme & Gemfile.
